name: CI/CD

on:
  push:
    branches: [ main, operators ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Run Tests
      run: mvn clean test

    - name: Build Application
      run: mvn clean package -DskipTests

    - name: Build Docker Image
      run: docker build -t calculator-api:test .

    - name: Test Docker Compose
      run: |
        docker-compose config
        docker-compose build

    - name: Messages
      if: success()
      run: |
        echo "All Tests okay"
        echo "Build completed"
        echo "Docker image built successfully"
        echo "Docker compose tested successfully"